### ISSUE TITLE
It show nothing while doing http://localhost:8181/system/console

### ISSUE THREAD

**Issue by kaushal9808** [mkroli/servicemix-docker#1]
I have use this image in docker it run in container fine but it does not show anything while i run in browser http:localhost:8181/system/console its shows connection refused in window 7

or how i can use this image in my application bundle.
please provide some reference.

i am new to docker.

**Comment by mkroli** [comment]
By default the webconsole feature is not installed. You can install it by executing

```
feature:install webconsole
```

in the servicemix shell.

However since you get `connection refused` instead of `404 - Not Found` I assume you either need to setup port forwarding from localhost to the container or you need to specify the container's address instead of localhost in your browser.

To get the IP address of the container use

```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' servicemix
```

where `servicemix` would be the name of the container.

**Comment by kaushal9808** [comment]
I have installed the docker on windows 7 
Please provide me solutions only for windows 7.
In my docker container the servicemix is installed like this
**CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
d73b4de1e0ca        mkroli/servicemix   "/opt/servicemix/bin/"   26 minutes ago      Up 26 minutes       1099/tcp, 8181/tcp, 44444/tcp, 61616/tcp, 127.0.0.1:8101->8101/tcp   servicemix**

after this i run the command
**docker run --name mix  --rm -i -t mkroli/servicemix /opt/servicemix/bin/**
it open the karaf console and after installing the 
karaf@root>feature:install webconsole
Error executing command: Can't install feature webconsole/0.0.0:
Error accessing mvn:org.apache.felix/org.apache.felix.metatype/1.0.12

we are getting access error while installing the webconsole

**Comment by mkroli** [comment]
I have no experience with docker on windows.
I assume you have some network issues with your docker installation.
